pipeline {
    agent any
    environment {
        ENV_NAME = 'dev'
        APP_NAME = 'firstspring-dev'
        APP_PORT = '9595'
        DOCKER_IMAGE = 'firstspring-app:dev-latest'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/Saket105/spring-docker-test'
            }
        }

        stage('Maven Build') {
            steps {
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Load Dev Config') {
            steps {
                script {
                    // read dev configuration
                    devConfig = readYaml file: 'ci/dev/values-dev.yml'
                    echo "Building for environment: ${devConfig.environment}"
                    echo "Server port: ${devConfig.server.port}"
                }
            }
        }

        stage('Docker Build') {
            steps {
                bat "docker build -t %DOCKER_IMAGE% ."
            }
        }

        stage('Deploy to Dev') {
            steps {
                script {
                    def port = 9595
                     bat """
                                    echo Stopping old container if exists...
                                    docker stop firstspring-dev || echo "No running container"

                                    echo Removing old container if exists...
                                    docker rm firstspring-dev || echo "No container to remove"

                                    echo Starting new container on port ${port}...
                                    docker run -d -p ${port}:${port} --name firstspring-dev firstspring-app:dev-latest --server.port=${port}
                                """
                }
            }
        }


        stage('Verify Dev Deployment'){
            steps{
                script{
                    def port = devConfig.server.port   // use the same loaded port
                    sleep(10)
                    bat "curl -f http://localhost:${port}/actuator/health || echo Health check failed but continuing"
                    echo "✅ DEV Deployment Successful!"
                    echo "🌐 Access DEV at: http://localhost:${port}"
                }
            }
        }
    }
    post{
        always{
            echo 'Dev pipeline execution completed'
        }
    }
}